github.com:
    users:
        thacker19:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: thacker19
